import { useState, useEffect } from 'react';
import { useApp } from '../../context/AppContext';
import { carbonService } from '../../services/apiService';
import { RadialBarChart, RadialBar, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts';
import jsPDF from "jspdf";
export default function CarbonSavings() {
  const { user, addNotification } = useApp();

const [stats, setStats] = useState({
  carbonSavingsKg: 0,
  fuelSavingsLiters: 0,
  moneySaved: 0,
  totalRidesCompleted: 0,
});
useEffect(() => {
  const loadCarbonSavings = async () => {
    try {
      const response = await carbonService.getCarbonSavings(user.id);
      setStats(response.data);
    } catch (error) {
      console.error(error);
      addNotification({
        title: "Error",
        message: "Could not load carbon savings.",
        type: "error",
      });
    }
  };

  if (user?.id) {
    loadCarbonSavings();
  }
}, [user]);
  const carbonSaved = stats.carbonSavingsKg;
const monthlyData = [
  carbonSaved * 0.05,
  carbonSaved * 0.10,
  carbonSaved * 0.18,
  carbonSaved * 0.26,
  carbonSaved * 0.35,
  carbonSaved * 0.45,
  carbonSaved * 0.55,
  carbonSaved * 0.65,
  carbonSaved * 0.75,
  carbonSaved * 0.85,
  carbonSaved * 0.93,
  carbonSaved
];

const months = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec"
];


const fuelSaved = stats.fuelSavingsLiters;
const moneySaved = stats.moneySaved;
const ridesCompleted = stats.totalRidesCompleted;

  const tips = [
    { icon: '🌱', text: '1 shared trip saves average 4.2 kg CO₂' },
    { icon: '🌳', text: `You've offset ${(carbonSaved / 21).toFixed(1)} trees worth of carbon` },
    { icon: '⛽', text: `${fuelSaved.toFixed(1)}L fuel saved = ₹${moneySaved}` },
    { icon: '🏭', text: 'Equivalent to turning off an AC for several hours' },
  ];

  const achievementData = [
    { name: 'CO₂ Goal', value: Math.min(100, (carbonSaved / 100) * 100), fill: '#00d4aa' },
  ];
  const downloadReport = () => {
  const doc = new jsPDF();

  // Header
  doc.setFillColor(16, 185, 129);
  doc.rect(0, 0, 210, 35, "F");

  doc.setFontSize(24);
  doc.setTextColor(255, 255, 255);
  doc.text("EcoRide", 20, 18);

  doc.setFontSize(14);
  doc.text("Carbon Savings Report", 20, 28);

  // Reset color
  doc.setTextColor(0);

  // Rider Info
  doc.setFontSize(12);

  doc.text(`Name : ${user?.name || "Rider"}`, 20, 50);
  doc.text(`Date : ${new Date().toLocaleDateString()}`, 20, 58);

  doc.line(20, 65, 190, 65);

  doc.setFontSize(18);
  doc.text("Environmental Summary", 20, 80);

  doc.setFontSize(13);

  doc.text(`Completed Shared Rides : ${ridesCompleted}`, 25, 95);

  doc.text(`Carbon Saved : ${carbonSaved.toFixed(2)} kg`, 25, 107);

  doc.text(`Fuel Saved : ${fuelSaved.toFixed(2)} Litres`, 25, 119);

  doc.text(`Money Saved : ₹${moneySaved}`, 25, 131);

  doc.text(
    `Trees Equivalent : ${(carbonSaved / 21).toFixed(1)}`,
    25,
    143
  );

  const ecoLevel =
    carbonSaved >= 100
      ? "Platinum"
      : carbonSaved >= 70
      ? "Gold"
      : carbonSaved >= 40
      ? "Silver"
      : "Bronze";

  doc.text(`Eco Level : ${ecoLevel}`, 25, 155);

  doc.line(20, 165, 190, 165);

  doc.setTextColor(16, 185, 129);
  doc.setFontSize(16);

  doc.text(
    "Thank you for helping reduce carbon emissions!",
    20,
    180
  );

  doc.setTextColor(120);

  doc.setFontSize(11);

  doc.text(
    "Generated by EcoRide AI Powered Carpooling System",
    20,
    192
  );

  doc.save("EcoRide_Carbon_Report.pdf");
};

  return (
    <>
      <div className="topbar">
        <div className="topbar-left">
          <h1>Carbon Savings 🌿</h1>
          <p>Your environmental impact</p>
        </div>
        <div className="topbar-right">
          <span className="badge badge-success">🌱 Eco Warrior</span>
        </div>
      </div>

      <div className="page-content">
        {/* Hero Carbon Card */}
        <div style={{
          background: 'linear-gradient(135deg, rgba(0,212,170,0.12) 0%, rgba(124,106,245,0.12) 100%)',
          border: '1px solid rgba(0,212,170,0.25)',
          borderRadius: 'var(--radius-xl)', padding: 40, marginBottom: 24,
          position: 'relative', overflow: 'hidden'
        }}>
          <div style={{ position: 'absolute', right: 30, top: '50%', transform: 'translateY(-50%)', fontSize: 120, opacity: 0.08 }}>🌍</div>
          <div style={{ position: 'relative' }}>
            <h2 style={{ fontSize: 22, marginBottom: 6 }}>Your Green Impact</h2>
            <p style={{ color: 'var(--text-muted)', fontSize: 14, marginBottom: 32 }}>
              Every shared ride makes a difference. Here's yours.
            </p>
            <div style={{ display: 'flex', gap: 40, flexWrap: 'wrap' }}>
              {[
                { icon: '💨', value: `${carbonSaved.toFixed(1)} kg`, label: 'CO₂ Saved', color: 'var(--accent-primary)' },
                { icon: '⛽', value: `${fuelSaved.toFixed(1)} L`, label: 'Fuel Saved', color: 'var(--accent-secondary)' },
                { icon: '💰', value: `₹${moneySaved.toLocaleString()}`, label: 'Money Saved', color: 'var(--accent-warning)' },
                { icon: '🚗', value: ridesCompleted, label: 'Shared Rides', color: 'var(--accent-blue)' },
              ].map((item, i) => (
                <div key={i} id={`carbon-stat-${i}`}>
                  <div style={{ fontSize: 36, marginBottom: 4 }}>{item.icon}</div>
                  <div style={{ fontSize: 36, fontWeight: 900, color: item.color, lineHeight: 1 }}>{item.value}</div>
                  <div style={{ fontSize: 13, color: 'var(--text-muted)', marginTop: 4 }}>{item.label}</div>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 24 }}>
          {/* Progress towards goal */}
          <div className="card">
            <h3 style={{ marginBottom: 20 }}>Monthly Goal Progress</h3>
            <div style={{ display: 'flex', alignItems: 'center', gap: 24 }}>
              <div style={{ width: 140, height: 140, position: 'relative', flexShrink: 0 }}>
                <ResponsiveContainer width="100%" height="100%">
                  <RadialBarChart cx="50%" cy="50%" innerRadius={45} outerRadius={65}
                    data={[{ value: Math.min(100, (carbonSaved / 100) * 100), fill: '#00d4aa' }]} startAngle={90} endAngle={-270}>
                    <RadialBar dataKey="value" cornerRadius={8} background={{ fill: 'rgba(255,255,255,0.05)' }} />
                  </RadialBarChart>
                </ResponsiveContainer>
                <div style={{ position: 'absolute', inset: 0, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}>
                  <div style={{ fontSize: 20, fontWeight: 800, color: 'var(--accent-primary)' }}>{Math.round(Math.min(100, (carbonSaved / 100) * 100))}%</div>
                  <div style={{ fontSize: 10, color: 'var(--text-muted)' }}>of goal</div>
                </div>
              </div>
              <div>
                <div style={{ marginBottom: 8 }}>
                  <div style={{ fontSize: 13, color: 'var(--text-muted)', marginBottom: 2 }}>Current</div>
                  <div style={{ fontSize: 22, fontWeight: 800, color: 'var(--accent-primary)' }}>{carbonSaved.toFixed(1)} kg</div>
                </div>
                <div>
                  <div style={{ fontSize: 13, color: 'var(--text-muted)', marginBottom: 2 }}>Monthly Goal</div>
                  <div style={{ fontSize: 22, fontWeight: 800 }}>100 kg</div>
                </div>
                <div style={{ marginTop: 12, fontSize: 12, color: 'var(--accent-primary)' }}>
                  {carbonSaved >= 100 ? '🎉 Goal Achieved!' : `🎯 ${(100 - carbonSaved).toFixed(1)} kg more to reach goal!`}
                </div>
              </div>
            </div>
          </div>

          {/* Green Tips */}
          <div className="card">
            <h3 style={{ marginBottom: 20 }}>Green Facts</h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
              {tips.map((tip, i) => (
                <div key={i} style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
                  <div style={{ fontSize: 22, flexShrink: 0 }}>{tip.icon}</div>
                  <div style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.5 }}>{tip.text}</div>
                </div>
              ))}
            </div>
          </div>
        </div>

     <div className="card" style={{ marginTop: 24 }}>
  <h3 style={{ marginBottom: 20 }}>🌍 Environmental Impact Summary</h3>

  <div
    style={{
      display: "grid",
      gridTemplateColumns: "repeat(auto-fit, minmax(220px,1fr))",
      gap: 18,
    }}
  >
    <div
      style={{
        padding: 18,
        borderRadius: 12,
        background: "rgba(0,212,170,0.08)",
        border: "1px solid rgba(0,212,170,0.2)",
      }}
    >
      <div style={{ fontSize: 32 }}>🌳</div>
      <h4 style={{ marginTop: 10 }}>Trees Equivalent</h4>
      <div
        style={{
          fontSize: 28,
          fontWeight: 800,
          color: "var(--accent-primary)",
        }}
      >
        {(carbonSaved / 21).toFixed(1)}
      </div>
      <p style={{ color: "var(--text-muted)", fontSize: 13 }}>
        Trees absorbing this amount of CO₂
      </p>
    </div>

    <div
      style={{
        padding: 18,
        borderRadius: 12,
        background: "rgba(124,106,245,0.08)",
        border: "1px solid rgba(124,106,245,0.2)",
      }}
    >
      <div style={{ fontSize: 32 }}>🚗</div>
      <h4 style={{ marginTop: 10 }}>Average CO₂ / Ride</h4>
      <div
        style={{
          fontSize: 28,
          fontWeight: 800,
          color: "var(--accent-secondary)",
        }}
      >
        {ridesCompleted > 0
          ? (carbonSaved / ridesCompleted).toFixed(1)
          : "0"}{" "}
        kg
      </div>
      <p style={{ color: "var(--text-muted)", fontSize: 13 }}>
        Average saving per completed ride
      </p>
    </div>

    <div
      style={{
        padding: 18,
        borderRadius: 12,
        background: "rgba(255,193,7,0.08)",
        border: "1px solid rgba(255,193,7,0.2)",
      }}
    >
      <div style={{ fontSize: 32 }}>🏅</div>
      <h4 style={{ marginTop: 10 }}>Eco Level</h4>

      <div
        style={{
          fontSize: 28,
          fontWeight: 800,
          color: "var(--accent-warning)",
        }}
      >
        {carbonSaved >= 100
          ? "Platinum"
          : carbonSaved >= 70
          ? "Gold"
          : carbonSaved >= 40
          ? "Silver"
          : "Bronze"}
      </div>

      <p style={{ color: "var(--text-muted)", fontSize: 13 }}>
        Keep sharing rides to level up!
      </p>
    </div>
  </div>
</div>

        {/* Share */}
        <div style={{
          marginTop: 24, background: 'linear-gradient(135deg, rgba(124,106,245,0.1), rgba(0,212,170,0.1))',
          border: '1px solid rgba(124,106,245,0.2)', borderRadius: 'var(--radius-lg)', padding: 24,
          display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 16, flexWrap: 'wrap'
        }}>
          <div>
            <h3 style={{ marginBottom: 4 }}>Share Your Impact 🌍</h3>
            <p style={{ fontSize: 13, color: 'var(--text-muted)' }}>Inspire your friends to carpool too!</p>
          </div>
          <div style={{ display: 'flex', gap: 10 }}>
            <button id="share-whatsapp" className="btn btn-secondary">📲 WhatsApp</button>
            <button id="share-twitter" className="btn btn-secondary">🐦 Twitter</button>
           <button
    id="download-report"
    className="btn btn-primary"
    onClick={downloadReport}
>📥 Download Report</button>
          </div>
        </div>
      </div>
    </>
  );
}
